Doc 4006 pc hotfix hci
NetAppDocs/hci pull request #234
Opened 2022-02-04 19:36 UTC by netapp-pcarriga

Updating links and removing SolidFire references

2022-02-07 17:48 UTC, netapp-dbagwell requested changes

2022-02-08 16:12 UTC, netapp-pcarriga commented on docs/task_hcc_upgrade_element_software.adoc
> +For NetApp HCI systems, go to the NetApp HCI software https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab[download page^] and download the latest storage node image.
@netapp-dbagwell Typo corrected

2022-02-10 11:24 UTC, netapp-pcarriga commented on docs/rn_compute_firmware_2.27.adoc
> +To download the Compute Firmware Bundle, go to the https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/Compute_Firmware_Bundle[NetApp HCI Compute Firmware B
@netapp-dbagwell Response from Nicole "We don't have older versions available. Only the latest storage or compute firmware package is ever available.  Hence why we just update the one page and don't have a newer version on the product page."

2022-02-10 11:39 UTC, netapp-pcarriga commented on docs/task_hcc_upgrade_element_software.adoc
> +. Download the storage upgrade package. For NetApp HCI systems, go to the NetApp HCI software https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab[download page^] and downl
Done

2022-02-10 11:40 UTC, netapp-pcarriga commented on docs/task_hcc_upgrade_management_node.adoc
> +. Download the management node ISO for https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab[NetApp HCI] from the NetApp Support Site to the management node virtual machine.
Done

2022-02-10 11:42 UTC, netapp-pcarriga commented on docs/task_mnode_install.adoc
> +. Download the OVA or ISO for your installation from the https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tabNetApp[NetApp HCI^] page on the NetApp Support Site.
Done

2022-02-11 16:52 UTC, netapp-dbagwell commented on docs/rn_compute_firmware_2.27.adoc
> +To download the Compute Firmware Bundle, go to the https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/Compute_Firmware_Bundle[NetApp HCI Compute Firmware B
Ok, that sounds familiar to me now. Thanks for confirming!

2022-02-11 16:56 UTC, merged